name: flutter_sms_service_example
description: "Demonstrates how to use the flutter_sms_service plugin."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sms_service:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
